version: "2"
services:
  app:
    build: .
    environment:
      PORT: "3000"
      BIND: "0.0.0.0"
      DATABASE_HOST: "postgres"
    ports:
      - "3000:3000"
    links:
      - postgres
  postgres:
    image: postgres:9.6