#!/usr/bin/env bash

# script/update: Update application to run for it's current checkout

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Updating db..."
# run all database migrations to ensure everything is up to date.
bin/rake db:create || true
bin/rake db:migrate
bin/rake db:seed